"""empty message

Revision ID: a0ef8c7a2fa5
Revises: 0a0ab0f78abc
Create Date: 2021-12-12 14:46:26.894432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0ef8c7a2fa5'
down_revision = '0a0ab0f78abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'icon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('icon', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
